CREATE USER NHIMC_CHATBOT IDENTIFIED BY NHIMC_CHATBOT_0124
DEFAULT TABLESPACE TBL_ETC01;

GRANT RESOURCE, CONNECT TO NHIMC_CHATBOT;

CREATE OR REPLACE VIEW NHIMC_DBA.NV_CHATUSER
(
     USID
    ,USER_NM
    ,DEPT_CD
    ,DEPT_NM
    ,PW
)
AS
SELECT C.USID,C.USER_NM,B.DEPT_CD,B.DEPT_NM,C.PW
FROM NHIMC_DBA.ERINMPMST A
   , NHIMC_DBA.AZCMMDEPT B
   , NHIMC_DBA.AZCMMUSER C
WHERE 1 = 1
  AND A.DUTY_SHPE_DVSN IN ('1', '3') --재직,휴직(근무형태구분(재직상태) : ER152)
  AND A.DUTY_DEPT = B.DEPT_CD                         --소속부서
  AND A.DUTY_DEPT_GVOD_DY BETWEEN B.DEPT_STR_DY AND B.DEPT_END_DY
  AND A.EMPL_NO = C.USID
  AND TO_CHAR (SYSDATE, 'YYYYMMDD') BETWEEN C.USER_STR_DY AND C.USER_END_DY
;

GRANT SELECT ON NHIMC_DBA.NV_CHATUSER TO NHIMC_CHATBOT;
