version: '1.0'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nhimc_chat-db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./script/initdb:/docker-entrypoint-initdb.d
    env_file: 
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 5432:5432
    networks:
      - nhimcchat-public

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: 
      - .env
    environment:
      TZ: "Asia/Seoul"  # timezone 설정 부분
    ports:
      - 8000:8000
    volumes:
      - ./backend/app/:/app/app
      - ./frontend/nginx/certbot/conf:/etc/letsencrypt
      - ./backend/logs:/logs
    networks:
      - nhimcchat-public
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      TZ: "Asia/Seoul"  # timezone 설정 부분
    env_file: 
      - .env
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx/logs:/var/log/nginx
      - ./frontend/nginx/Nginx/tmp:/tmp
      #- ./frontend/build:/usr/share/nginx/html
    command: /bin/sh -c "/conf.sh && nginx -g 'daemon off;'"
    networks:
      - nhimcchat-public
    depends_on:
      - backend

volumes:
  app-db-data:

networks:
  nhimcchat-public:
    # Allow setting it to false for testing
    #external: true