version: '1.0'

services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: nhimc_chat-db
    volumes:
      - nhimcchat-db-data:/var/lib/postgresql/data/pgdata
      - ./script/initdb:/docker-entrypoint-initdb.d
    env_file: 
      - prd.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - LANG=ko_KR.euckr
      - LC_COLLATE=C
      - LC_CTYPE=C
      - TZ=Asia/Seoul
      - POSTGRES_INITDB_ARGS=--encoding=EUC_KR --lc-collate=C --lc-ctype=C
    ports:
      - 5432:5432
    networks:
      - nhimcchat-public
  
  cache_db:
    image: redis/redis-stack
    container_name: nhimc_chat-cache-db
    ports:
      - 6379:6379
    networks:
      - nhimcchat-public

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: 
      - prd.env
    environment:
      TZ: "Asia/Seoul"  # timezone 설정 부분
    ports:
      - 8000:8000
    volumes:
      - ./backend/app/:/app/app
      - ./frontend/nginx/certbot/conf:/etc/letsencrypt
      - ./backend/logs:/logs
      - ./backend/files:/app/files
    networks:
      - nhimcchat-public
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      TZ: "Asia/Seoul"  # timezone 설정 부분
    env_file: 
      - prd.env
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx/logs:/var/log/nginx
      - ./frontend/nginx/Nginx/tmp:/tmp
    command: /bin/sh -c "/conf.sh && nginx -g 'daemon off;'"
    networks:
      - nhimcchat-public
    depends_on:
      - backend

volumes:
  app-db-data:
  nhimcchat-db-data:

networks:
  nhimcchat-public:
    # Allow setting it to false for testing
    #external: true