"""empty message

Revision ID: 0eac59fbf0a9
Revises: bfc3be0170ac
Create Date: 2025-03-18 19:59:32.106628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0eac59fbf0a9'
down_revision: Union[str, None] = 'bfc3be0170ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmdata', sa.Column('orgin_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('tmdata', 'origin_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmdata', 'origin_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tmdata', 'orgin_key')
    # ### end Alembic commands ###
