"""empty message

Revision ID: 1b631219c4e3
Revises: 5098e0a7e2c1
Create Date: 2025-03-19 13:45:52.251178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1b631219c4e3'
down_revision: Union[str, None] = '5098e0a7e2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_full_md5_llm_cache_idx', table_name='full_md5_llm_cache')
    op.drop_index('ix_full_md5_llm_cache_llm', table_name='full_md5_llm_cache')
    op.drop_index('ix_full_md5_llm_cache_prompt_md5', table_name='full_md5_llm_cache')
    op.drop_table('full_md5_llm_cache')
    op.add_column('tmresult', sa.Column('item_seq', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmresult', 'item_seq')
    op.create_table('full_md5_llm_cache',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_md5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('llm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='full_md5_llm_cache_pkey')
    )
    op.create_index('ix_full_md5_llm_cache_prompt_md5', 'full_md5_llm_cache', ['prompt_md5'], unique=False)
    op.create_index('ix_full_md5_llm_cache_llm', 'full_md5_llm_cache', ['llm'], unique=False)
    op.create_index('ix_full_md5_llm_cache_idx', 'full_md5_llm_cache', ['idx'], unique=False)
    # ### end Alembic commands ###
