"""empty message

Revision ID: 1b631219c4e3
Revises: 5098e0a7e2c1
Create Date: 2025-03-19 13:45:52.251178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1b631219c4e3'
down_revision: Union[str, None] = '5098e0a7e2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('tmresult', sa.Column('item_seq', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmresult', 'item_seq')
    # ### end Alembic commands ###
