"""empty message

Revision ID: 200b7130d6c2
Revises: bcc145881e8c
Create Date: 2025-01-23 15:21:24.171857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '200b7130d6c2'
down_revision: Union[str, None] = 'bcc145881e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmmessages', sa.Column('full_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmmessages', 'full_prompt')
    # ### end Alembic commands ###
