"""empty message

Revision ID: 20b39c9ac587
Revises: 9bbf67dc49bd
Create Date: 2025-02-13 13:43:40.445348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '20b39c9ac587'
down_revision: Union[str, None] = '9bbf67dc49bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('thought_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('chatbot', 'response_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('response_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chatbot', 'thought_prompt')
    # ### end Alembic commands ###
