"""empty message

Revision ID: 271b7bf67381
Revises: d654b1e9ee7b
Create Date: 2024-11-19 15:49:19.535760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '271b7bf67381'
down_revision: Union[str, None] = 'd654b1e9ee7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deptusage',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dept_llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('input_token', sa.Integer(), nullable=False),
    sa.Column('output_token', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_llm_id'], ['deptllm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deptusage')
    # ### end Alembic commands ###
