"""empty message

Revision ID: 2e885a780567
Revises: 0eac59fbf0a9
Create Date: 2025-03-19 10:50:15.001880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2e885a780567'
down_revision: Union[str, None] = '0eac59fbf0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmdata', sa.Column('origin_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tmdata', 'orgin_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmdata', sa.Column('orgin_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tmdata', 'origin_key')
    # ### end Alembic commands ###
