"""empty message

Revision ID: 338644e2fa4f
Revises: c6e557a04512
Create Date: 2025-01-08 13:15:00.313790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '338644e2fa4f'
down_revision: Union[str, None] = 'c6e557a04512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmchats', sa.Column('instruct_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('tmchats_instrction_id_fkey', 'tmchats', type_='foreignkey')
    op.create_foreign_key(None, 'tmchats', 'tminstruct', ['instruct_id'], ['id'])
    op.drop_column('tmchats', 'instrction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmchats', sa.Column('instrction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tmchats', type_='foreignkey')
    op.create_foreign_key('tmchats_instrction_id_fkey', 'tmchats', 'tminstruct', ['instrction_id'], ['id'])
    op.drop_column('tmchats', 'instruct_id')
    # ### end Alembic commands ###
