"""empty message

Revision ID: 3e9a53296a5a
Revises: 8c28db2966be
Create Date: 2025-03-21 16:56:56.171103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3e9a53296a5a'
down_revision: Union[str, None] = '8c28db2966be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmmaster', sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmmaster', 'comments')
    # ### end Alembic commands ###
