"""empty message

Revision ID: 5098e0a7e2c1
Revises: c3d4c0737fb8
Create Date: 2025-03-19 13:25:39.478645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5098e0a7e2c1'
down_revision: Union[str, None] = 'c3d4c0737fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('tmresult', 'item_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmresult', 'item_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
