"""empty message

Revision ID: 56edf8bf8993
Revises: 66b68b7dabfd
Create Date: 2024-11-05 17:02:40.587186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '56edf8bf8993'
down_revision: Union[str, None] = '66b68b7dabfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thought', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('messages', sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tools')
    op.drop_column('messages', 'thought')
    # ### end Alembic commands ###
