"""empty message

Revision ID: 5d08838b3854
Revises: dc96b741e2b8
Create Date: 2025-04-21 11:22:05.446926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d08838b3854'
down_revision: Union[str, None] = 'dc96b741e2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent')
    op.add_column('chatbot', sa.Column('is_agent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'is_agent')
    op.create_table('agent',
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delete_yn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bot_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instruct_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_llm_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dept_llm_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_file_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('bottools_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('search_kwargs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bottools_id'], ['bottools.id'], name='agent_bottools_id_fkey'),
    sa.ForeignKeyConstraint(['dept_llm_id'], ['deptllm.id'], name='agent_dept_llm_id_fkey'),
    sa.ForeignKeyConstraint(['user_file_id'], ['userfiles.id'], name='agent_user_file_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='agent_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_llm_id'], ['userllm.id'], name='agent_user_llm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_pkey')
    )
    # ### end Alembic commands ###
