"""empty message

Revision ID: 65bbf69a8eb6
Revises: e39592a8633a
Create Date: 2024-12-27 16:46:17.611890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '65bbf69a8eb6'
down_revision: Union[str, None] = 'e39592a8633a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
