"""empty message

Revision ID: 7743bbaf02bd
Revises: 7c3c258f4aef
Create Date: 2025-02-07 10:14:30.268631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7743bbaf02bd'
down_revision: Union[str, None] = '7c3c258f4aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('instruct_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatbot', sa.Column('response_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('chatbot_user_prompt_id_fkey', 'chatbot', type_='foreignkey')
    op.drop_column('chatbot', 'user_prompt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('user_prompt_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('chatbot_user_prompt_id_fkey', 'chatbot', 'userprompt', ['user_prompt_id'], ['id'])
    op.drop_column('chatbot', 'response_prompt')
    op.drop_column('chatbot', 'instruct_prompt')
    # ### end Alembic commands ###
