"""empty message

Revision ID: 7b50f9cff550
Revises: cd7837612aaa
Create Date: 2025-02-14 11:50:12.427132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7b50f9cff550'
down_revision: Union[str, None] = 'cd7837612aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chatbot_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'chatbot', ['chatbot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'chatbot_id')
    
    # ### end Alembic commands ###
