"""empty message

Revision ID: 7c3c258f4aef
Revises: b3d168457e54
Create Date: 2025-02-06 15:17:53.598677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7c3c258f4aef'
down_revision: Union[str, None] = 'b3d168457e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'api_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tools', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tools', 'api_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
