"""empty message

Revision ID: 8c28db2966be
Revises: f1b122fc7067
Create Date: 2025-03-19 14:00:30.116142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8c28db2966be'
down_revision: Union[str, None] = 'f1b122fc7067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 기존 PK 제약조건 삭제
    op.drop_constraint(
        constraint_name='tmresult_pkey',
        table_name='tmresult',
        type_='primary'
    )
    
    # 2. 새로운 PK 제약조건 생성
    op.create_primary_key(
        'tmresult_pkey',
        'tmresult',
        ['master_id', 'data_id', 'seq', 'item_seq']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='tmresult_pkey',
        table_name='tmresult',
        type_='primary'
    )
    op.create_primary_key(
        'tmresult_pkey',
        'tmresult',
        ['master_id', 'data_id', 'seq']
    )
    
    # ### end Alembic commands ###
