"""empty message

Revision ID: b3d168457e54
Revises: dabbd319d416
Create Date: 2025-02-06 15:13:32.128053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b3d168457e54'
down_revision: Union[str, None] = 'dabbd319d416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottools',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('chatbot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tools_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.ForeignKeyConstraint(['tools_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chatbot', sa.Column('bottools_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('chatbot', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_constraint('chatbot_tools_id_fkey', 'chatbot', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot', 'bottools', ['bottools_id'], ['id'])
    op.drop_column('chatbot', 'tools_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('tools_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbot', type_='foreignkey')
    op.create_foreign_key('chatbot_tools_id_fkey', 'chatbot', 'tools', ['tools_id'], ['id'])
    op.drop_column('chatbot', 'is_public')
    op.drop_column('chatbot', 'bottools_id')
    op.drop_table('bottools')
    # ### end Alembic commands ###
