"""empty message

Revision ID: bcc145881e8c
Revises: dee4a9bad223
Create Date: 2025-01-21 13:50:44.615708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bcc145881e8c'
down_revision: Union[str, None] = 'dee4a9bad223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userusage', sa.Column('tm_llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'userusage', 'tmllm', ['tm_llm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userusage', type_='foreignkey')
    op.drop_column('userusage', 'tm_llm_id')
    # ### end Alembic commands ###
