"""empty message

Revision ID: c4618fea3d6a
Revises: 65bbf69a8eb6
Create Date: 2024-12-30 13:48:39.422711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c4618fea3d6a'
down_revision: Union[str, None] = '65bbf69a8eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'url')
    # ### end Alembic commands ###
