"""empty message

Revision ID: c6e557a04512
Revises: c90e8001d03f
Create Date: 2025-01-08 11:40:47.765998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c6e557a04512'
down_revision: Union[str, None] = 'c90e8001d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmchats', 'instrction_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmchats', 'instrction_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
