"""empty message

Revision ID: c8b3bdd55bec
Revises: 5d08838b3854
Create Date: 2025-04-25 09:44:55.017265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c8b3bdd55bec'
down_revision: Union[str, None] = '5d08838b3854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('is_agent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'is_agent')
    # ### end Alembic commands ###
