"""empty message

Revision ID: cd7837612aaa
Revises: 20b39c9ac587
Create Date: 2025-02-13 14:39:04.362724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cd7837612aaa'
down_revision: Union[str, None] = '20b39c9ac587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfiles', sa.Column('embedding_user_llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('userfiles_embedding_model_id_fkey', 'userfiles', type_='foreignkey')
    op.create_foreign_key(None, 'userfiles', 'userllm', ['embedding_user_llm_id'], ['id'])
    op.drop_column('userfiles', 'embedding_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfiles', sa.Column('embedding_model_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userfiles', type_='foreignkey')
    op.create_foreign_key('userfiles_embedding_model_id_fkey', 'userfiles', 'llm', ['embedding_model_id'], ['id'])
    op.drop_column('userfiles', 'embedding_user_llm_id')
    # ### end Alembic commands ###
