"""empty message

Revision ID: d654b1e9ee7b
Revises: 4d7f53f536b2
Create Date: 2024-11-18 13:28:19.885698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd654b1e9ee7b'
down_revision: Union[str, None] = '4d7f53f536b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deptapikey',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dept_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('api_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['dept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deptllm',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dept_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('api_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['deptapikey.id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['dept.id'], ),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deptllm')
    op.drop_table('deptapikey')
    # ### end Alembic commands ###
