"""empty message

Revision ID: da27586a915e
Revises: f94bbe6e7f6f
Create Date: 2025-05-07 17:21:29.759720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'da27586a915e'
down_revision: Union[str, None] = 'f94bbe6e7f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systemprompt', sa.Column('contents', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('systemprompt', 'instruct_prompt')
    op.drop_column('systemprompt', 'response_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systemprompt', sa.Column('response_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('systemprompt', sa.Column('instruct_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('systemprompt', 'contents')
    # ### end Alembic commands ###
