"""empty message

Revision ID: dc96b741e2b8
Revises: 3e9a53296a5a
Create Date: 2025-04-15 13:10:10.554029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'dc96b741e2b8'
down_revision: Union[str, None] = '3e9a53296a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bot_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instruct_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('dept_llm_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_file_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('bottools_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('search_kwargs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['bottools_id'], ['bottools.id'], ),
    sa.ForeignKeyConstraint(['dept_llm_id'], ['deptllm.id'], ),
    sa.ForeignKeyConstraint(['user_file_id'], ['userfiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_llm_id'], ['userllm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tmdata', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmexecset', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tminstruct', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmmaster', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmresult', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmtopic', sa.Column('load_cplt_yn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmtopic', 'load_cplt_yn')
    op.drop_column('tmresult', 'load_cplt_yn')
    op.drop_column('tmmaster', 'load_cplt_yn')
    op.drop_column('tminstruct', 'load_cplt_yn')
    op.drop_column('tmexecset', 'load_cplt_yn')
    op.drop_column('tmdata', 'load_cplt_yn')
    op.drop_table('agent')
    # ### end Alembic commands ###
