"""empty message

Revision ID: e251bb132701
Revises: 200b7130d6c2
Create Date: 2025-01-24 09:53:33.977156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e251bb132701'
down_revision: Union[str, None] = '200b7130d6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tmexecset_extract_id_fkey', 'tmexecset', type_='foreignkey')
    op.drop_table('tmextract')
    op.drop_column('tmexecset', 'extract_id')
    op.add_column('tminstruct', sa.Column('is_final', sa.Boolean(), nullable=True))
    op.add_column('tmtopic', sa.Column('sql', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmtopic', 'sql')
    op.drop_column('tminstruct', 'is_final')
    op.add_column('tmexecset', sa.Column('extract_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('tmexecset_extract_id_fkey', 'tmexecset', 'tmextract', ['extract_id'], ['id'])
    op.create_table('tmextract',
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delete_yn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sql', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['tmtopic.id'], name='tmextract_topic_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tmextract_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tmextract_pkey')
    )
    # ### end Alembic commands ###
