"""empty message

Revision ID: e39592a8633a
Revises: bec88a4eab5f
Create Date: 2024-11-22 10:14:05.138867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e39592a8633a'
down_revision: Union[str, None] = 'bec88a4eab5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deptusage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deptusage',
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delete_yn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dept_llm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usage_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('input_token', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_token', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dept_llm_id'], ['deptllm.id'], name='deptusage_dept_llm_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='deptusage_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deptusage_pkey')
    )
    # ### end Alembic commands ###
