"""empty message

Revision ID: f5b2fe6dc9ce
Revises: 7b50f9cff550
Create Date: 2025-02-14 13:25:29.621792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f5b2fe6dc9ce'
down_revision: Union[str, None] = '7b50f9cff550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_full_md5_llm_cache_idx', table_name='full_md5_llm_cache')
    op.drop_index('ix_full_md5_llm_cache_llm', table_name='full_md5_llm_cache')
    op.drop_index('ix_full_md5_llm_cache_prompt_md5', table_name='full_md5_llm_cache')
    op.drop_table('full_md5_llm_cache')
    op.drop_table('full_llm_cache')
    op.add_column('chats', sa.Column('chatbot_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'chats', 'chatbot', ['chatbot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'chatbot_id')
    op.create_table('full_llm_cache',
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('llm', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prompt', 'llm', 'idx', name='full_llm_cache_pkey')
    )
    op.create_table('full_md5_llm_cache',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_md5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('llm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='full_md5_llm_cache_pkey')
    )
    op.create_index('ix_full_md5_llm_cache_prompt_md5', 'full_md5_llm_cache', ['prompt_md5'], unique=False)
    op.create_index('ix_full_md5_llm_cache_llm', 'full_md5_llm_cache', ['llm'], unique=False)
    op.create_index('ix_full_md5_llm_cache_idx', 'full_md5_llm_cache', ['idx'], unique=False)
    # ### end Alembic commands ###
