"""empty message

Revision ID: f94bbe6e7f6f
Revises: c8b3bdd55bec
Create Date: 2025-05-07 16:50:30.741151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f94bbe6e7f6f'
down_revision: Union[str, None] = 'c8b3bdd55bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systemprompt', sa.Column('work_detail_cd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systemprompt', 'work_detail_cd')
    # ### end Alembic commands ###
