"""empty message

Revision ID: fae2539b8d34
Revises: 052740c4017e
Create Date: 2025-03-11 14:33:10.016150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fae2539b8d34'
down_revision: Union[str, None] = '052740c4017e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('temperature', sa.Float(), nullable=True))
    op.drop_column('chatbot', 'temparature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('temparature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('chatbot', 'temperature')
    # ### end Alembic commands ###
