"""empty message

Revision ID: fd17f53a65fd
Revises: 338644e2fa4f
Create Date: 2025-01-08 13:43:05.659740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fd17f53a65fd'
down_revision: Union[str, None] = '338644e2fa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmchats', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmchats', 'description')
    # ### end Alembic commands ###
